version: '3'

services:
  mysql-db:
    image: mysql:5.7
    container_name: "db"
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: 123456
    expose: 
      - 3306
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  server:
    #build: .
    build:
      context: .
      dockerfile: Dockerfile
    image: maozain/pathway-reviewer-backend
    container_name: "Pathway-Backend"
    depends_on:
      - mysql-db
    volumes:
      - .:/pathway
      - '/pathway/node_modules'
    tty: true
    expose: 
      - 6000
    environment:
      API_HOST: "http://localhost:3336"
      APP_SERVER_PORT: 6000
      MYSQL_HOST_IP: mysql-db
    ports:
      - '6000:6000'
    command: sh -c "cd /pathway && node app.js"
  web:
    #build: ./web
    build:
      context: ./web
      dockerfile: Dockerfile
    image: maozain/pathway-reviewer-frontend
    container_name: "Pathway-Frontend"
    command: sh -c "export PORT=3336 && npm start"
    volumes:
      - ./web:/web
      - '/web/node_modules'
    tty: true
    expose: 
      - 3336
    ports:
      - '3336:3336'
